### ISSUE TITLE
Modern Authentication

### ISSUE THREAD

**Issue by qaziAnis** [chrishasz/spgo#100]
Our Organization uses Modern authentication for Office 365, and has disabled Basic Authentication using ADFS rules. Are you planning to support Modern authentication

**Comment by koltyakov** [comment]
These are supported https://github.com/s-kainet/node-sp-auth/wiki

**Comment by chrishasz** [comment]
hello @qaziAnis - Did you find what you need in the documentation that @koltyakov provided, or are you still having errors?

**Comment by qaziAnis** [comment]
This doesn't solve my error, the ADFS server has below rule 
"Allow all intranet traffic only for browser and modern authentication clients". This rule prevents SpGo from getting authorized to access Sharepoint online. Our requests gets authenticated (Active directory verifies that the user credentials are right), but the rule prevents us from getting authorization to Sharepoint online.

**Comment by s-KaiNet** [comment]
@qaziAnis the only way for you to make it work is to use [SharePoint Online addin only authentication](https://github.com/s-kainet/node-sp-auth/wiki/SharePoint-Online-addin-only-authentication). Username authentication will not work.

**Comment by qaziAnis** [comment]
Thanks , that resolved our issue
