### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by danielgmota** [chrishasz/spgo#107]
- Issue Type: `Performance`
- Extension Name: `spgo`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\daniel.mota\SiteGo.spgo-unresponsive.cpuprofile.txt

[SiteGo.spgo-unresponsive.cpuprofile.txt](https://github.com/chrishasz/spgo/files/3962120/SiteGo.spgo-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

Obs: The Publish was always slow, at about one minute

**Comment by danielgmota** [comment]
PS: This issue was generate by Visual Studio Code. If it isn't useful, i'll can close the issue

**Comment by chrishasz** [comment]
@danielgmota - Thanks for sharing that report. I'll run the `cpuprofile` output through the VSCode profiler and see if there are any obvious perf issues.

I see you are experincing slow publishing. What kind of SharePoint farm are you working with? 

Do you get this error often?

**Comment by danielgmota** [comment]
The team use SP online, we just customize web parts in VScode for publish some files js/css. Total files size at about 3 MB.

This error happended only once
