### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KowsikRajan** [chrishasz/spgo#108]
The SPGo Commands are not getting executed on some of the machine which is very weird  

- Issue Type: `Performance`
- Extension Name: `spgo`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.42.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\KowsikR\SiteGo.spgo-unresponsive.cpuprofile.txt
[SiteGo.spgo-unresponsive.cpuprofile.txt](https://github.com/chrishasz/spgo/files/4197694/SiteGo.spgo-unresponsive.cpuprofile.txt)
`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by chrishasz** [comment]
Hello @KowsikRajan 

Thanks for sharing this. Did the user notice specific performance degradation while using SPGo? Can you describe the operations they were performing when this occurred?

Can you send the performance dump file to me at spgo@chrishasz.com and I will run it through the VSCode profiler.

**Comment by chrishasz** [comment]
Closed, old.
