### ISSUE TITLE
ID3242: The security token could not be authenticated or authorized

### ISSUE THREAD

**Issue by vishalsharma3105** [chrishasz/spgo#109]
I have workspace configured and trying to checkout file.

I have recently changed my domain password, post which I am not being prompted for username and password on cs code, and while checking out file getting this error

**Comment by chrishasz** [comment]
Hello @vishalsharma3105 

Have you configured SPGo to store credentials? If so, what happens if you disable this option and try to log in again?

**Comment by chrishasz** [comment]
I did some further research and authentication error ID3242 is an ADFS authentication error. Are you using ADFS via a Secure Token Service to access SharePoint? How is your authentication set up?

Please post your SPGo.json file and I can help troubleshoot.

**Comment by vishalsharma3105** [comment]
Hi... The issue got resolved by restarting the system. And , we were using
the sharepoint crendentials.

**Comment by chrishasz** [comment]
Good news! I’m going to close this issue.
