### ISSUE TITLE
SPgo stoped work, it don't find any commands.

### ISSUE THREAD

**Issue by cryongen** [chrishasz/spgo#113]
Vscode just updated to Version: 1.45.1, and spgo stoped work, it don't find any commands.

Command 'SPGo: Configure workspace' resulted in an error (command 'spgo.configureWorkspace' not found)
Command 'SPGo: Reload Configuration' resulted in an error (command 'spgo.reloadConfiguration' not found)
Command 'SPGo: Retrieve folder' resulted in an error (command 'spgo.retrieveFolder' not found)
Command 'SPGo: Check out file' resulted in an error (command 'spgo.checkOutFile' not found)

**Comment by cryongen** [comment]
> Vscode just updated to Version: 1.45.1, and spgo stoped work, it don't find any commands.
> 
> Command 'SPGo: Configure workspace' resulted in an error (command 'spgo.configureWorkspace' not found)
> Command 'SPGo: Reload Configuration' resulted in an error (command 'spgo.reloadConfiguration' not found)
> Command 'SPGo: Retrieve folder' resulted in an error (command 'spgo.retrieveFolder' not found)
> Command 'SPGo: Check out file' resulted in an error (command 'spgo.checkOutFile' not found)

I installed  previous version of spgo (1.6.2), end it worked again.

**Comment by chrishasz** [comment]
Hello @cryongen -

Can you respond with you `spgo.json` file? I am testing SPGo 1.6.3 against VSCode 1.45.1 and I am not able to replicate your issue.

Also, are there any other logs in either the `Extension` or `SPGo` output windows?

**Comment by chrishasz** [comment]
Closing as old. @cryongen if you are still seeing this issue, please reopen this issue.
