### ISSUE TITLE
"cannot read property 'firstChild' of undefined" error?

### ISSUE THREAD

**Issue by alainnaw** [chrishasz/spgo#114]
Hi there -
I was following along with the video tutorial but I couldn't get the space to populate.  Here's my SPGo.json file: 
```
{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://xxx.sharepoint.com/teams/xxx",
    "workspaceRoot": "c:\\Users\\alainna\\site",
    "publishWorkspaceOptions": {
        "destinationFolder": "/",
        "globPattern": c:\\Users\\alainna\\site\\src\\**\\*.*",
        "localRoot": "c:\\Users\\alainna\\site\\src"
    },
    "publishingScope": "SaveOnly",
    "authenticationType": "Digest"
}
```

Here's the output (snipped some "==" so it wouldn't initiate a scroll in the issue report): 

```
[5/19/2020, 8:49:23 AM] =============     ERROR  =================

[5/19/2020, 8:49:23 AM] Cannot read property 'firstChild' of undefined
[5/19/2020, 8:49:23 AM] Error Detail:
[5/19/2020, 8:49:23 AM] ----------------------
[5/19/2020, 8:49:23 AM] {}
[5/19/2020, 8:49:23 AM] ===============
```

Any thoughts? Thank you!

**Comment by alainnaw** [comment]
I suspect this may be because it's a /teams/ and not /sites/.

**Comment by chrishasz** [comment]
Hello @alainnaw 

A couple notes/questions:
1. From your config file, it looks like you are configuring SPGo's advanced publishing features to publish files to sharepoint without mapping them to your local folder - for instance if you are building/deploying a React, Angular, or Vue-based solution. Is this the case? If so, there is a syntax errors in your config: You need to add an opening quote `"` to the `"globPattern"` propety.
2. If you are not using advanced publishing, and just want to synchronize files directly, I would recommend using the `remoteFolders` property instead  Can you try the following changes:
``` json
{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://xxx.sharepoint.com/teams/xxx",
    "publishingScope": "SaveOnly",
    "authenticationType": "Digest"
    "remoteFolders" : [
        "/SiteAssets/**/*",
    ]
}
```
- Of course, you would replace `xxx` and `SiteAssets` with the name of your team, and the folder within the site that you want to replicate. You can find documentation on the `Populate Workspace` command [here.](https://www.chrishasz.com/spgo/commands/populate-workspace)

If you are still having problems, can you describe which files you want to synchronize locally and I'll help you get your config file set up correctly.

Thanks for using SPGo!

**Comment by alainnaw** [comment]
Hey Chris - Thanks for the quick reply.  I did as asked, but still no joy.  I'm just a site collection owner that wants to do some customizing to her SharePoint site.  I would ideally like to populate the whole tree so I have extra flexibility (and extra dangerousness ;))
```
{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://xxx.sharepoint.com/teams/xxx",
    "publishingScope": "SaveOnly",
    "authenticationType": "Digest",
    "remoteFolders" : [
        "/SiteAssets/**/*"
    ]
}
```

Thanks for the help!
Alainna

**Comment by chrishasz** [comment]
@alainnaw - Thanks for the update.

I'm going to try to replicate the issue using team sites. Do you know if this site was created via the SP UI, or via the Teams app?

Can you do a quick test with a site in your tenant that is on the `/sites` managed path just to make sure the issue isn't related to authentication or something else?

**Comment by chrishasz** [comment]
Separately - SPGo does support working with full Site Collection hierarchies (trees), so once we get this initial issue resolved, I can help you configure you `spgo.json` file to pull down all the files you need.

**Comment by alainnaw** [comment]
Hey Chris - 

I don't have any sites on the /sites path unfortunately.

**Comment by chrishasz** [comment]
Hello @alainnaw - I've been trying to test this a number of ways, and I am, so far, unable to reproduce the bug. I've tried creating a team site via teams, as well as team sites via the Site Collection Manager.

A couple question for you:
1. when you made the changes to your `spgo.json` file did you get the same error or a different error?
2. do any other commands work? Are you able to use the [Retrieve Folder](https://www.chrishasz.com/spgo/commands/retrieve-folder) command or are you able to create a new file via VSCode?
3. Are you using any sort of custom authentication, e.g. ADFS, or does your site use SPO/Digest?

Thanks for working with me on this. Hopefully we can get this resolved soon.

**Comment by alainnaw** [comment]
Hey @chrishasz, 

I got the same error with each spgo.json file iteration I tried.  

I tried the retrieve folder command and I received the same error.  

I don't think we're using any kind of unique authentication.  

Are there any debugging flags I can add in to increase verbosity of the output? 

Thank you for taking the time to help me out here.  I appreciate it.

-AW

**Comment by chrishasz** [comment]
Hello @alainnaw -

Unfortunately VSCode is still preventing me from supporting O365 MFA natively. Are you able to define an app password for SPGo on your site?

If so, here is how to configure SPGo with App passwords: 
https://www.chrishasz.com/spgo/authentication/two-factor-authentication

Here is the documentation for configuring App Passwords:
https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords#create-new-app-passwords

**Comment by chrishasz** [comment]
Hello @alainnaw -

I am in the process of adding "Addin Only" authentication to SPGo. Maybe this will work for you. Are you able to create an Addin registration on your team site(s)?

**Comment by chrishasz** [comment]
Hello @alainnaw - SPGo supports Addin-only authentication as of version 1.7.0. You can find documentation on how to configure Addin-only authentication [here](https://www.chrishasz.com/spgo/authentication/addin-only-authentication).
