### ISSUE TITLE
Populating Workspace issue

### ISSUE THREAD

**Issue by kalaram20** [chrishasz/spgo#117]
I am using NTLM for on-prem sp 2016, populate the local workspace continuously running. No error and nothing happening. The notification shows multiple instances of "Populating workspaces". Any thoughts on this?

Issue:

Nothing happening when I try to populate the workspace 
  
    "publishingScope": "SaveOnly",
    "authenticationType": "NTLM",
    "remoteFolders": [
        "/Style Library/eboardScripts/cScripts"
    ]

In  VS code notification, I am seeing so many "Populating workspace" running.

Expected:  It should populate files from the on-prem sp 2016 site.

Note: I have VS code on my desktop but SharePoint deployed in a VM. I am trying to connect to a non-development environment. Configuration worked fine and .json file created but when I try to populate folder from that site I get nothing. I am the owner of that site. Not sure what went wrong! 

![image](https://user-images.githubusercontent.com/59364792/85034879-89770480-b150-11ea-944e-43d7df1d9756.png)

**Comment by chrishasz** [comment]
Hello @kalaram20 

Sorry for the long delay. I’ve seen a couple other users with NTLM problems lately, so there must be something going on.

Are there any messages in the SPGo output logs?

If you are able, I would also ask you to open the VSCode debug console and record any errors you se there for me.

Thanks for using SPGo. I hope we can get this resolved quickly!

**Comment by chrishasz** [comment]
Hello @kalaram20. Are you still seeing this issue?

**Comment by chrishasz** [comment]
I'm closing this issue due to age. Please reopen if you are still experiencing the issue.
