### ISSUE TITLE
Smart Card Authentication

### ISSUE THREAD

**Issue by bada004** [chrishasz/spgo#118]
Is it possible to use SPGo with a site that only allows for smart card authentication?

**Comment by chrishasz** [comment]
Hello @bada004 

SPGo uses [node-sp-auth](https://github.com/s-KaiNet/node-sp-auth) for SharePoint authentication, so we would need to work with the author of that package to implement smart card authentication.

Can you provide more details about the Smart Card implementation you use, including the vendor and links to any developer wikis? This will help me determine if support is possible.

**Comment by chrishasz** [comment]
Closing this issue. SPGo will continue to support authentication through `node-sp-auth`.
