### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hasankoroglu** [chrishasz/spgo#120]
Hi,

i'm working with webpack env. every time i bundled the js package i have to publish bundle.js with shift+alt+p combination.

is there any easy way to publish bundle.js automatically after bundling.

Thanks for this great tool.

**Comment by chrishasz** [comment]
Hello @hasankoroglu!

SPGo does not support a native method for automated publishing on minify, but there is a good solution for this scenario that involves setting up automated deployment scripts which integrate directly into VSCode.

Check out the link [here](http://blog.arvosys.com/2016/08/30/front-end-sharepoint-projects-synced-and-safe/index.html). This blog post was written by the same person who authored by the libraries I use behind the scenes in SPGo.

Hope this helps!

**Comment by hasankoroglu** [comment]
Thank you very much, spgo saving our lives everyday :)
