### ISSUE TITLE
Request: Add On-Demand authentication

### ISSUE THREAD

**Issue by ckreling** [chrishasz/spgo#126]
**_I do not know how to remove the bug label - sorry_**

The feature I am requesting is for SP On-Demand authentication which is supported in node-sp-auth.  This would need SPGo to pop-up the browser dialog (probably using electron) to allow authentication via the ws-fed cookie.

It's supported in node-sp-auth but just not in SPGo currently.  The developer of node-sp-auth says that the PingFederate ADFS is different than OOTB ADFS and thus that will no longer work.

I used to use digest but PingFederate does not support that.

* **I'm submitting a ...**

  * [ ] bug report
  * [x] feature request

* **What is the current behavior?**
Cannot login to SP now that we use PingFederate and WS-Fed for identity management
* **If the current behavior is a bug, please**
  
  * Your `spgo.json` file (You may replace corporate PII with "xxx")
  * Steps to reproduce

* **What is the expected behavior?**

* **Please tell us about your environment:**
  
  * OS and Version OS X Catalina
  * SharePoint Location (Online vs. On Premise) Online
  * Authentication Type (e.g. Digest, NTFS, ADFS) Was using Digest - no longer working as we moved from Microsoft ADFS to PingFederate WS-Fed

**Comment by chrishasz** [comment]
Hello @ckreling - SPGo supports Addin-only authentication as of version 1.7.0. I hope this solves your access issues!

Closing this issue.
