### ISSUE TITLE
sharepoint authentication with sso

### ISSUE THREAD

**Issue by joacko14atchurchofjesuschrist** [chrishasz/spgo#129]
im triying to use spgo fow develop sharepoint site with my company, but when i try lo populate local folder i use my company account then enter the password and nothing happens.

i tried with an educational account and all works fine, the difference that i can look is... my company sharepoint tenant sends me to a custom login and after returns me to sharepoint, anyone have some experience with something like that.

**Comment by chrishasz** [comment]
Hello @joacko14atchurchofjesuschrist - sorry for the late response.

At this time, SPGo does not support Authentication that requires an interactive login. I did add Addin-ony authentication to SPGo in version 1.7.0. This can be used as a workaround for environments that require interactive login by registering SPGo as an Addin.

Let me know if this solves the problem.

**Comment by chrishasz** [comment]
Closing.
