### ISSUE TITLE
feature request: Pop-up message 

### ISSUE THREAD

**Issue by mcallegario** [chrishasz/spgo#133]
Hi Chris,

Congratulations on your initiative.

I have a small suggestion:

Currently when I save a file and it is not checked in to min the SPGo shows a message on the output console, to draw more attention it would be possible to also display the message in the VSCode pop-up, as shown in the example below:
![image](https://user-images.githubusercontent.com/44271732/102361574-2399f700-3f92-11eb-8f9f-a29cc79cbbf9.png)

Thanks
Marcos

**Comment by chrishasz** [comment]
Hello @mcallegario - I encountered this same issue when I was testing the latest SPGo release. I will make sure that upload errors due to checked out files are displayed in a popup in the next version of SPGo.
