### ISSUE TITLE
Bug: Always publishing minor

### ISSUE THREAD

**Issue by aka963** [chrishasz/spgo#150]
Hi  @chrishasz ,

Even though the publishing scope was set to "Major", on save it is publishing the minor version.

To tackle this issue I had to revert to version 1.6.3. 

Can the latest version behave the same in terms of publishing?

**Comment by chrishasz** [comment]
Hello @aka963 I will take a look at this issue this weekend and publish a fix if I can repro.

Thanks for using SPGo!

**Comment by chrishasz** [comment]
Hello @aka963 I just published SPGo version 1.7.3 to the VSCode marketpace which should resolve this issue.

Please reopen this issue if you are still experiencing the bug after uploading.

**Comment by aka963** [comment]
Hi @chrishasz ,

Thank you the issue is resolved.
