### ISSUE TITLE
Keeps asking for Authentication

### ISSUE THREAD

**Issue by CPritch** [chrishasz/spgo#71]
We're currently experiencing an issue where authentication has to be re-entered on every new session.

Here's our SPGo config setup:

```
{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://contoso.sharepoint.com/",
    "publishingScope": "PublishMinor",
    "authenticationType": "Digest",
    "storeCredentials": true,
    "remoteFolders": [
        "/SiteAssets/**/*"
    ]
}
```

We have folder redirection set up in our company if that provides any helpful env info. If you need anything more from me just say.

Awesome extension btw! Our department is moving to this currently as it allows for us to tentatively move away from SPD and more into VSCode for all dev work.

**Comment by sg-chrishasz** [comment]
Hello @CPritch 

I'm really glad to hear that you and your team is enjoying SPGo! 

regarding the credentialing issues. SPGo stores the hashed credentials in your local user's temp folder, using a filename based on the unique URL of your SharePoint site. I'm not sure if folder redirection is somehow randomizing the filename, or if your corporate policy is preventing/clearing your user's temp data frequently.

Can you do me a favor and log in to your SP Site, with `storeCredentials` set to true, and then let me know if you see any files in your local temp folder: `C:\Users\<your name>\AppData\Local\Temp\SPGo`. SPGo credential files would have a name like `https___tenant_sharepoint_com_sites_sitename.json`.

Thanks!

**Comment by CPritch** [comment]
Hi @sg-chrishasz 

Thanks for the reply. Upon taking a look at the output of VS Code and the local Temp folder it definitely popped up with a message indicating that it couldn't find the necessary JSON.

![image](https://user-images.githubusercontent.com/29358433/52407649-c21cbd80-2ac8-11e9-8271-fe63408b15aa.png)

When I end up looking in the Temp folder I can see all the profiles that I currently have open in VS Code. But none from previous sessions on another working day.

![image](https://user-images.githubusercontent.com/29358433/52407838-4111f600-2ac9-11e9-91db-8eb4517c2458.png)

It definitely looks like SPGo is correctly saving and picking up these files. It definitely looks like what is happening is not related to SPGo but some sort of environment issue. I'll speak with our infrastructure dept and see if this could be the cause. Probably something wiping out these files on re-boot and login.

Cheers again for the help, I'll close this ticket.

**Comment by CPritch** [comment]
@sg-chrishasz 

And after a final investigation we had a scheduled task running from our device management system. It was clearing out our user Temp folder. Again, fantastic extension. Being able to sync a classic SharePoint and integrate with our Vs Code workflow has been a godsend.

**Comment by koltyakov** [comment]
@CPritch, so giving a "star" could be a good contribution to the project to be more visible by new folks! ;)

**Comment by sg-chrishasz** [comment]
@CPritch - Thanks for the detailed response! 

In a positive turn, VSCode 1.31 added support for [extension-specific data storage](https://code.visualstudio.com/updates/v1_31#_global-storage-path). I'm going to investigate using this feature to store the hashed password files so that file durability is tied to the extension, rather than a less-permanent temp file.

I'll provide an update once I've finished the research.

**Comment by chrishasz** [comment]
@CPritch I just release SPGo 1.6.1 to the VSCode marketplace which uses extension-specific storage rather than the OS Temp file. This should resolve your issue. Please give it a try and let me know if it works for you.

Thanks for your patience!

**Comment by chrishasz** [comment]
I'm going to close this issue as resolved. Please reopen or create a new issue if the bug persists.
