### ISSUE TITLE
[Feature Request] Check File Changes

### ISSUE THREAD

**Issue by CPritch** [chrishasz/spgo#79]
Hi There,

I have a suggestion for a feature. This should help with issues of old synced workspaces causing file regression.

If the last sync of a file or workspace is older then X amount of time then check the server for any changes or modified date greater than last sync. That way someone opening an old workspace will get the latest version of a file without having to re-sync the entire workspace.

Maybe an option for sync on open workspace in the SPGo config? We're just encountering cases of different file versions synced on different machines, it's an easy fix with version control but I imagine the problem gets harder to figure out in larger scale organisations with large amounts of site assets.

**Comment by chrishasz** [comment]
@CPritch -

Thanks for the PR. Code looks great, I've merged into master. I need to put together a quick bugfix for the `Compare File With Server` command, and I'll package these for the VSCode Marketplace.
