### ISSUE TITLE
You must fill out all required properties before checking in this document.

### ISSUE THREAD

**Issue by saulsilva99** [chrishasz/spgo#82]
Hi!

When I try to publish a major version this error occurs.

> You must fill out all required properties before checking in this document. 

What I really want to do is save the file and automatically check in my masterpage, but my masterpage is  checkout and when i check in via sharepoint designer it says " We can't do that for you because the file is no longer checked out or has been deleted. "

**Comment by chrishasz** [comment]
Hello @saulsilva99. Does the library that you are checking files in/out of have custom or required fields on them?

**Comment by chrishasz** [comment]
Closing this issue do to age. @saulsilva99 please reopen if you are still experiencing the issue and can provide the details I requested above.
