### ISSUE TITLE
Populate Local Workspace - Not working 

### ISSUE THREAD

**Issue by stevenrlp** [chrishasz/spgo#87]
Hi,

I have been trying for hours to get SPGo to work with a SharePoint 2010 site and I have no idea why it is not working and it would be good if someone could point out what I am doing wrong or if there is an issue with the extension.

I am attempting to connect to an old SharePoint 2010 site and use source control on some custom pages I developed on there and every time I attempt to connect I keep getting a 404 error and no other details.

I can connect to the site via a web browser and I can even open the site without the need of SPGo but without source control.

Can anyone advise what I am doing wrong.

This is the SPGo.json I am currently using, I have attempted adding additional properties like "remoteFolders" and nothing seems to work.

Does SPGo even work with SharePoint 2010?

`{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "https://docs.MYDOMAIN.com/Support/Revenue Assurance",
    "publishingScope": "SaveOnly",
    "authenticationType": "NTLM"
}`

The error I am getting is:

```
================================     ERROR     ================================

404 - "404 NOT FOUND"
Error Detail:
----------------------
```

Any help would be great, thanks!

**Comment by koltyakov** [comment]
SP2010 is not supported. Internally, REST API is used for save/download/etc. operations. In 2010, there were not REST API (in its usual form, only first legacy REST endpoint). So, even if NTML auth works with SP2010 other functionality doesn't.

**Comment by stevenrlp** [comment]
Thank you for clearing that up, I did look around and try to find what is supported but it does not seem to be documented anywhere.
