### ISSUE TITLE
SPGo: Compare File With Server not working

### ISSUE THREAD

**Issue by tockata** [chrishasz/spgo#91]
Hello @sg-chrishasz ,
 
"SPGo: Compare File With Server" has stopped working. We tried it on several PCs and it is not working. All other actions work fine.

The error that is shown when trying to compare a file with the server is:
"File is not checked out."

**System information:**
**Visual Studio Code version:**
Version: 1.35.1 (system setup)
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**SPGo version: 1.4.0**

**Comment by chrishasz** [comment]
Hello @tockata 

I can confirm that there is a bug with the `Compare File With Server` command in SPGO 1.4.0.

I'll release a fix for this in 1.4.1

**Comment by tockata** [comment]
Thank you very much!
I hope this will be soon as this is a very important functionality :)

**Comment by chrishasz** [comment]
I've submitted a PR to fix this error in a downstream dependency. You can follow here: https://github.com/koltyakov/sppull/pull/35

Once we get this resolved, I'll update SPPull and release the fix.

**Comment by chrishasz** [comment]
@tockata SPGo version 1.4.1 is live on the [VSCode marketplace](https://marketplace.visualstudio.com/items?itemName=SiteGo.spgo) and resolves this bug.

**Comment by tockata** [comment]
Hi @chrishasz ,
the new version is not working at all - all commands throw an error. For example for "Populate Workspace" - command SpGo:populateWorkspace not found. You can replicate the error using the Command Palette /Ctrl+Shift+P/.

I have reverted to version 1.3.5 which is working fine.

**Comment by chrishasz** [comment]
Hello @tockata 

I just published v1.4.2 to the Visual Studio Marketplace. Turns out there were a number of dependency errors which required updated npm packages to resolve. Please get the latest build and let me know if you still see this error.

**Comment by tockata** [comment]
Thank you @chrishasz !
I can confirm that 1.4.2 is working fine now.

Thank you again for your quick response.
