### ISSUE TITLE
command 'spgo.retrieveFolder' not found

### ISSUE THREAD

**Issue by mbr55aa** [chrishasz/spgo#93]
I get a notification "command 'spgo.%any_command_name%' not found" on try to call any SPGo command. 
I tried to use clean VSC and SPGo installation, did not help.
Issue occurs on both Windows and Ubuntu.

**Comment by chrishasz** [comment]
Yes, I’m receiving reports of issues with build 1.4.1. Can you revert to 1.4.0 until I have a chance to fix this today?

**Comment by mbr55aa** [comment]
That helped. Thank you!

**Comment by tarcisiopqdt** [comment]
How I can return to 1.4.0 version?

**Comment by tarcisiopqdt** [comment]
I got it!

**Comment by chrishasz** [comment]
Everyone- I found the error with packaging that prevented SPGo from loading, fixed it, and published an update version 1.4.2 to the Visual Studio Marketplace.

Please confirm that v1.4.2 works. Thanks!

**Comment by mknig** [comment]
Hi, sorry but spgo.retrieveFolder doesn't work for me.  Local files are not updated by new sitecollection files. I am using version is 1.4.2.  How can I return to 1.4.0

**Comment by mknig** [comment]
found the "install another option" on the extention. I had to install 1.3.5 to make it work as expected.

**Comment by chrishasz** [comment]
Hello @mknig -

Are you working against the root web of the root site collection? I am tracking an active issue with users downloading files, using Glob notation, from that specific web here: #94

**Comment by mknig** [comment]
Hello Chrishasz, 

thanks for your reply. 

Yes. I use /**/* to download all files form the server. 1.3.5 is working fine, but 1.4.X abort the download immediately. 



Von: "Chrishasz" <notifications@github.com> 
An: "chrishasz/spgo" <spgo@noreply.github.com> 
CC: "mknig" <michael.koenig@tapetenagentur.de>, "Mention" <mention@noreply.github.com> 
Gesendet: Montag, 8. Juli 2019 19:45:26 
Betreff: Re: [chrishasz/spgo] command 'spgo.retrieveFolder' not found (#93) 



Hello @mknig - 

Are you working against the root web of the root site collection? I am tracking an active issue with users downloading files, using Glob notation, from that specific web here: #94

**Comment by chrishasz** [comment]
@mknig we have determined a root cause for this issue. I’ll have a build out in the next day.

**Comment by chrishasz** [comment]
@mknig Version 1.4.3 has been published to the Visual Studio Marketplace. Please update to the latest version and confirm here if the issue is resolved.
