### ISSUE TITLE
Populate Local Workspace: Cannot read property of undefined

### ISSUE THREAD

**Issue by Jwmotley** [chrishasz/spgo#97]
Cannot populate local workspace. Keeps requesting credentials

Console error: 

Configuration file reloaded
================================     ERROR     ================================

Cannot read property 'length' of undefined
Error Detail:
----------------------
{}
===============================================================================

SPGo.json:
{
    "sourceDirectory": "src",
    "sharePointSiteUrl": "http://xxxxxxxxx.sharepoint.com/sites/x-xxx/Playbook",
    "publishingScope": "SaveOnly",
    "authenticationType": "Digest",
    "remoteFolders": [
        "/SiteAssets",
        "/SiteAssets/**/*.*"
    ],
    "storeCredentials": true
}

**Comment by Jwmotley** [comment]
Oh, I should also mention, VSCode on a Mac.

**Comment by chrishasz** [comment]
Hello @Jwmotley - Can you confirm if Playbook is the name of a subsite? The `sharePointSiteUrl` property should point to the root of a site, and not a folder or document library within the site.

**Comment by chrishasz** [comment]
Closing as old. Please reopen this issue with new information if the error is still persisting.
