### ISSUE TITLE
Get server version automatically

### ISSUE THREAD

**Issue by mesh7s** [chrishasz/spgo#99]
Hello,

Is there a way to get server version to automatically overwrite the local?

**Comment by mlung1** [comment]
This function is needed for sure.  I see that it can compare my local to the server version, but how do you just tell it to bring down that specific server version to work from?

**Comment by chrishasz** [comment]
All- I like this idea. Right now you can use the `retrieveFolder` command with the full path of the file, but that is not a great user experience. 

I plan to release an update this week with a new command to `Get Server Version` with a shortcut of `alt+shift+g`

**Comment by mesh7s** [comment]
That’s wonderful news, an awesome addition also would be to have a flag for a checked out file, just like the “check” mark in the SP Designer.

**Comment by mlung1** [comment]
Love it!  Like the status indicator idea as well if it's possible with VS
Code.

**Comment by chrishasz** [comment]
I have just published SPGo 1.4.4 to the VSCode Marketplace which supports getting the server version of both files and entire folders.

**Comment by chrishasz** [comment]
@mlung1 @mesh7s 

This feature is a common request, and something I would like to implement. VSCode does not support this exact functionality - the limitation is changing the file icon dynamically for each file.

That said, my current thinking is that I could add a new menu to the left nav where I could display a list of all files that are checked out to you, similar to the current github integration. As a bonus, creating a full panel for interracting with SharePoint would allow for editing of other information such as web properties.
